version: '3.8'
services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: sports_medicine_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4a1khFjT
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sports_medicine_control.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql

volumes:
  postgres_data:
